security.protocol=SSL

ssl.truststore.location=/mnt/c/Users/ankur/Downloads/Kafka/kafka_2.13-3.9.2/ssl/kafka.server.truststore.jks
ssl.truststore.password=localhost

ssl.endpoint.identification.algorithm=
